FROM node:16-alpine
WORKDIR /app

COPY package.json .
RUN npm install

# we can remove/comment the below copy command in development when volume is referenced.
# See docker-compose.yml for volume bookmarks.
COPY . .

CMD ["npm", "start"]